Vagrant.configure("2") do |config|

  # VM1: Public web server
  config.vm.define "webserver" do |webserver|

    # Operating system
    webserver.vm.box = "generic/debian12"
    webserver.vm.provider "virtualbox" do |vb|
      vb.name = "webserver-vm"           
      vb.memory = "1024"                 # Set memory size (1GB)
      vb.cpus = 1                        # Set number of CPUs
    end

    # public network with dynamic IP
    webserver.vm.network "public_network"

    # Shared folder between host and VM
    webserver.vm.synced_folder "C:/Shared", "/mnt/shared"  
    webserver.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y apache2
      sudo systemctl start apache2
    SHELL
    end

  end