Vagrant.configure("2") do |config|

  # VM1: Public web server
  config.vm.define "webserver" do |webserver|

    webserver.vm.box = "generic/debian12"
    webserver.vm.provider "virtualbox" do |vb|
      vb.name = "webserver-vm"           
      vb.memory = "1024"            
      vb.cpus = 1                     
    end

    webserver.vm.network "public_network"
    webserver.vm.synced_folder "C:/Shared", "/mnt/shared"  
    webserver.vm.provision "shell", path: "install_script.sh"
    end

    # VM2: Private server
  config.vm.define "privateserver" do |privateserver|

    privateserver.vm.box = "generic/debian12"
    privateserver.vm.provider "virtualbox" do |vb|
      vb.name = "private-server-vm"
      vb.memory = "1024"               
      vb.cpus = 1                     
    end


    privateserver.vm.network "private_network", ip: "192.168.50.4"
    privateserver.vm.synced_folder "C:/Shared", "/mnt/shared"
    privateserver.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y apache2
    sudo systemctl start apache2
  SHELL
  end

  # VM3: Public server with static IP
  config.vm.define "publicserver" do |publicserver|

    publicserver.vm.box = "generic/debian12"
    publicserver.vm.provider "virtualbox" do |vb|
      vb.name = "public-server-vm"
      vb.memory = "1024"                
      vb.cpus = 1                    
    end

    publicserver.vm.network "public_network", bridge: "Realtek RTL8822CE 802.11ac PCIe Adapter"
    publicserver.vm.synced_folder "C:/Shared", "/mnt/shared"
  end

end