config.vm.define "webserver" do |webserver|

  webserver.vm.box = "generic/debian12"
  webserver.vm.provider "virtualbox" do |vb|
    vb.name = "webserver-vm"           
    vb.memory = "1024"            
    vb.cpus = 1                     
  end

  webserver.vm.network "public_network"
  privateserver.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y nginx
    sudo systemctl start nginx
SHELL
  end