Vagrant.configure("2") do |config|

  config.vm.define "webserver" do |webserver|
    webserver.vm.box = "generic/ubuntu2004"
    webserver.vm.provider "virtualbox" do |vb|
      vb.name = "webserver-vm"
      vb.memory = "1024"
      vb.cpus = 1
    end

    webserver.vm.network "public_network"
    webserver.vm.provision "shell", path: "install_nginx_script.sh"
  end

end