Vagrant.configure("2") do |config|

  config.vm.define "webserver" do |webserver|
    webserver.vm.box = "generic/ubuntu2204"  
    webserver.vm.provider "virtualbox" do |vb|
      vb.name = "webserver-vm"
      vb.memory = "1024"
      vb.cpus = 1
    end

    webserver.vm.network "public_network"
    webserver.vm.provision "shell", inline: <<-SHELL
      echo "Updating package list..."
      sudo apt-get update

      echo "Installing Nginx from the official repository..."
      sudo apt-get install -y nginx

      echo "Adding PPA repository for Nginx..."
      sudo apt-get install -y software-properties-common
      sudo add-apt-repository -y ppa:nginx/stable
      sudo apt-get update

      echo "Installing Nginx from PPA..."
      sudo apt-get install -y nginx

      echo "Removing PPA repository and reverting to the official version of Nginx..."
      sudo apt-get install -y ppa-purge
      sudo ppa-purge -y ppa:nginx/stable

      echo "Starting Nginx..."
      sudo systemctl start nginx

      echo "Checking Nginx status..."
      sudo systemctl status nginx

      echo "Script execution completed!"
    SHELL
  end

end